# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_streaming_pb2 as audio__streaming__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.stream_stream(
                '/com.baidu.acu.pie.AsrService/send',
                request_serializer=audio__streaming__pb2.AudioFragmentRequest.SerializeToString,
                response_deserializer=audio__streaming__pb2.AudioFragmentResponse.FromString,
                _registered_method=True)


class AsrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.stream_stream_rpc_method_handler(
                    servicer.send,
                    request_deserializer=audio__streaming__pb2.AudioFragmentRequest.FromString,
                    response_serializer=audio__streaming__pb2.AudioFragmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.baidu.acu.pie.AsrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.baidu.acu.pie.AsrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.baidu.acu.pie.AsrService/send',
            audio__streaming__pb2.AudioFragmentRequest.SerializeToString,
            audio__streaming__pb2.AudioFragmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
