# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_streaming.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='audio_streaming.proto',
  package='com.baidu.acu.pie',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61udio_streaming.proto\x12\x11\x63om.baidu.acu.pie\"\xc7\x02\n\x0bInitRequest\x12\x1a\n\x12\x65nable_long_speech\x18\x01 \x01(\x08\x12\x14\n\x0c\x65nable_chunk\x18\x02 \x01(\x08\x12\x19\n\x11\x65nable_flush_data\x18\x03 \x01(\x08\x12\x12\n\nproduct_id\x18\x04 \x01(\t\x12\x1a\n\x12sample_point_bytes\x18\x05 \x01(\r\x12\x18\n\x10send_per_seconds\x18\x06 \x01(\x01\x12\x13\n\x0bsleep_ratio\x18\x07 \x01(\x01\x12\x10\n\x08\x61pp_name\x18\x08 \x01(\t\x12\x11\n\tlog_level\x18\t \x01(\r\x12\x11\n\tuser_name\x18\n \x01(\t\x12\x13\n\x0b\x65xpire_time\x18\x0b \x01(\t\x12\r\n\x05token\x18\x0c \x01(\t\x12\x30\n\x07version\x18\r \x01(\x0e\x32\x1f.com.baidu.acu.pie.ProtoVersion\"X\n\x14\x41udioFragmentRequest\x12\x14\n\x0csequence_num\x18\x01 \x01(\r\x12\x16\n\x0esend_timestamp\x18\x02 \x01(\x04\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"r\n\x13\x41udioFragmentResult\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12\x12\n\nserial_num\x18\x05 \x01(\t\"\xb1\x01\n\x15\x41udioFragmentResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x1f.com.baidu.acu.pie.ResponseType\x12>\n\x0e\x61udio_fragment\x18\x04 \x01(\x0b\x32&.com.baidu.acu.pie.AudioFragmentResult*j\n\x0cProtoVersion\x12\x0f\n\x0bUNKNOWN_VER\x10\x00\x12\r\n\tVERSION_1\x10\x01\x12\r\n\tVERSION_2\x10\x02\x12\r\n\tVERSION_3\x10\x03\x12\r\n\tVERSION_4\x10\x04\x12\r\n\tVERSION_5\x10\x05*3\n\x0cResponseType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x11\n\rFRAGMENT_DATA\x10\x01\x32k\n\nAsrService\x12]\n\x04send\x12\'.com.baidu.acu.pie.AudioFragmentRequest\x1a(.com.baidu.acu.pie.AudioFragmentResponse(\x01\x30\x01\x62\x06proto3')
)

_PROTOVERSION = _descriptor.EnumDescriptor(
  name='ProtoVersion',
  full_name='com.baidu.acu.pie.ProtoVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_VER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_4', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION_5', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=760,
  serialized_end=866,
)
_sym_db.RegisterEnumDescriptor(_PROTOVERSION)

ProtoVersion = enum_type_wrapper.EnumTypeWrapper(_PROTOVERSION)
_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='com.baidu.acu.pie.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAGMENT_DATA', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=868,
  serialized_end=919,
)
_sym_db.RegisterEnumDescriptor(_RESPONSETYPE)

ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
UNKNOWN_VER = 0
VERSION_1 = 1
VERSION_2 = 2
VERSION_3 = 3
VERSION_4 = 4
VERSION_5 = 5
UNKNOWN_TYPE = 0
FRAGMENT_DATA = 1



_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='com.baidu.acu.pie.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_long_speech', full_name='com.baidu.acu.pie.InitRequest.enable_long_speech', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_chunk', full_name='com.baidu.acu.pie.InitRequest.enable_chunk', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_flush_data', full_name='com.baidu.acu.pie.InitRequest.enable_flush_data', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='com.baidu.acu.pie.InitRequest.product_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_point_bytes', full_name='com.baidu.acu.pie.InitRequest.sample_point_bytes', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='send_per_seconds', full_name='com.baidu.acu.pie.InitRequest.send_per_seconds', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sleep_ratio', full_name='com.baidu.acu.pie.InitRequest.sleep_ratio', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='com.baidu.acu.pie.InitRequest.app_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='com.baidu.acu.pie.InitRequest.log_level', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='com.baidu.acu.pie.InitRequest.user_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire_time', full_name='com.baidu.acu.pie.InitRequest.expire_time', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='com.baidu.acu.pie.InitRequest.token', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.baidu.acu.pie.InitRequest.version', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=372,
)


_AUDIOFRAGMENTREQUEST = _descriptor.Descriptor(
  name='AudioFragmentRequest',
  full_name='com.baidu.acu.pie.AudioFragmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_num', full_name='com.baidu.acu.pie.AudioFragmentRequest.sequence_num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='send_timestamp', full_name='com.baidu.acu.pie.AudioFragmentRequest.send_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_data', full_name='com.baidu.acu.pie.AudioFragmentRequest.audio_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=462,
)


_AUDIOFRAGMENTRESULT = _descriptor.Descriptor(
  name='AudioFragmentResult',
  full_name='com.baidu.acu.pie.AudioFragmentResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='com.baidu.acu.pie.AudioFragmentResult.start_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='com.baidu.acu.pie.AudioFragmentResult.end_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='com.baidu.acu.pie.AudioFragmentResult.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completed', full_name='com.baidu.acu.pie.AudioFragmentResult.completed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_num', full_name='com.baidu.acu.pie.AudioFragmentResult.serial_num', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=578,
)


_AUDIOFRAGMENTRESPONSE = _descriptor.Descriptor(
  name='AudioFragmentResponse',
  full_name='com.baidu.acu.pie.AudioFragmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='com.baidu.acu.pie.AudioFragmentResponse.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='com.baidu.acu.pie.AudioFragmentResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.baidu.acu.pie.AudioFragmentResponse.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_fragment', full_name='com.baidu.acu.pie.AudioFragmentResponse.audio_fragment', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=758,
)

_INITREQUEST.fields_by_name['version'].enum_type = _PROTOVERSION
_AUDIOFRAGMENTRESPONSE.fields_by_name['type'].enum_type = _RESPONSETYPE
_AUDIOFRAGMENTRESPONSE.fields_by_name['audio_fragment'].message_type = _AUDIOFRAGMENTRESULT
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['AudioFragmentRequest'] = _AUDIOFRAGMENTREQUEST
DESCRIPTOR.message_types_by_name['AudioFragmentResult'] = _AUDIOFRAGMENTRESULT
DESCRIPTOR.message_types_by_name['AudioFragmentResponse'] = _AUDIOFRAGMENTRESPONSE
DESCRIPTOR.enum_types_by_name['ProtoVersion'] = _PROTOVERSION
DESCRIPTOR.enum_types_by_name['ResponseType'] = _RESPONSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUEST,
  __module__ = 'audio_streaming_pb2'
  # @@protoc_insertion_point(class_scope:com.baidu.acu.pie.InitRequest)
  ))
_sym_db.RegisterMessage(InitRequest)

AudioFragmentRequest = _reflection.GeneratedProtocolMessageType('AudioFragmentRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOFRAGMENTREQUEST,
  __module__ = 'audio_streaming_pb2'
  # @@protoc_insertion_point(class_scope:com.baidu.acu.pie.AudioFragmentRequest)
  ))
_sym_db.RegisterMessage(AudioFragmentRequest)

AudioFragmentResult = _reflection.GeneratedProtocolMessageType('AudioFragmentResult', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOFRAGMENTRESULT,
  __module__ = 'audio_streaming_pb2'
  # @@protoc_insertion_point(class_scope:com.baidu.acu.pie.AudioFragmentResult)
  ))
_sym_db.RegisterMessage(AudioFragmentResult)

AudioFragmentResponse = _reflection.GeneratedProtocolMessageType('AudioFragmentResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOFRAGMENTRESPONSE,
  __module__ = 'audio_streaming_pb2'
  # @@protoc_insertion_point(class_scope:com.baidu.acu.pie.AudioFragmentResponse)
  ))
_sym_db.RegisterMessage(AudioFragmentResponse)



_ASRSERVICE = _descriptor.ServiceDescriptor(
  name='AsrService',
  full_name='com.baidu.acu.pie.AsrService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=921,
  serialized_end=1028,
  methods=[
  _descriptor.MethodDescriptor(
    name='send',
    full_name='com.baidu.acu.pie.AsrService.send',
    index=0,
    containing_service=None,
    input_type=_AUDIOFRAGMENTREQUEST,
    output_type=_AUDIOFRAGMENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASRSERVICE)

DESCRIPTOR.services_by_name['AsrService'] = _ASRSERVICE

# @@protoc_insertion_point(module_scope)
