# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\x12\x11\x63om.baidu.acu.pie\"\xdb\x02\n\x0bInitRequest\x12\x1a\n\x12\x65nable_long_speech\x18\x01 \x01(\x08\x12\x14\n\x0c\x65nable_chunk\x18\x02 \x01(\x08\x12\x19\n\x11\x65nable_flush_data\x18\x03 \x01(\x08\x12\x12\n\nproduct_id\x18\x04 \x01(\t\x12\x1a\n\x12sample_point_bytes\x18\x05 \x01(\r\x12\x18\n\x10send_per_seconds\x18\x06 \x01(\x01\x12\x13\n\x0bsleep_ratio\x18\x07 \x01(\x01\x12\x10\n\x08\x61pp_name\x18\x08 \x01(\t\x12\x11\n\tlog_level\x18\t \x01(\r\x12\x11\n\tuser_name\x18\n \x01(\t\x12\x13\n\x0b\x65xpire_time\x18\x0b \x01(\t\x12\r\n\x05token\x18\x0c \x01(\t\x12\x30\n\x07version\x18\r \x01(\x0e\x32\x1f.com.baidu.acu.pie.ProtoVersion\x12\x12\n\nextra_info\x18\x0e \x01(\t\"X\n\x14\x41udioFragmentRequest\x12\x14\n\x0csequence_num\x18\x01 \x01(\r\x12\x16\n\x0esend_timestamp\x18\x02 \x01(\x04\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"r\n\x13\x41udioFragmentResult\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12\x12\n\nserial_num\x18\x05 \x01(\t\"\xb1\x01\n\x15\x41udioFragmentResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x1f.com.baidu.acu.pie.ResponseType\x12>\n\x0e\x61udio_fragment\x18\x04 \x01(\x0b\x32&.com.baidu.acu.pie.AudioFragmentResult*j\n\x0cProtoVersion\x12\x0f\n\x0bUNKNOWN_VER\x10\x00\x12\r\n\tVERSION_1\x10\x01\x12\r\n\tVERSION_2\x10\x02\x12\r\n\tVERSION_3\x10\x03\x12\r\n\tVERSION_4\x10\x04\x12\r\n\tVERSION_5\x10\x05*3\n\x0cResponseType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x11\n\rFRAGMENT_DATA\x10\x01\x32k\n\nAsrService\x12]\n\x04send\x12\'.com.baidu.acu.pie.AudioFragmentRequest\x1a(.com.baidu.acu.pie.AudioFragmentResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROTOVERSION']._serialized_start=780
  _globals['_PROTOVERSION']._serialized_end=886
  _globals['_RESPONSETYPE']._serialized_start=888
  _globals['_RESPONSETYPE']._serialized_end=939
  _globals['_INITREQUEST']._serialized_start=45
  _globals['_INITREQUEST']._serialized_end=392
  _globals['_AUDIOFRAGMENTREQUEST']._serialized_start=394
  _globals['_AUDIOFRAGMENTREQUEST']._serialized_end=482
  _globals['_AUDIOFRAGMENTRESULT']._serialized_start=484
  _globals['_AUDIOFRAGMENTRESULT']._serialized_end=598
  _globals['_AUDIOFRAGMENTRESPONSE']._serialized_start=601
  _globals['_AUDIOFRAGMENTRESPONSE']._serialized_end=778
  _globals['_ASRSERVICE']._serialized_start=941
  _globals['_ASRSERVICE']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
