// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: audio_streaming.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoVersion int32

const (
	ProtoVersion_UNKNOWN_VER ProtoVersion = 0
	ProtoVersion_VERSION_1   ProtoVersion = 1
	ProtoVersion_VERSION_2   ProtoVersion = 2
	ProtoVersion_VERSION_3   ProtoVersion = 3
	ProtoVersion_VERSION_4   ProtoVersion = 4
	ProtoVersion_VERSION_5   ProtoVersion = 5
)

// Enum value maps for ProtoVersion.
var (
	ProtoVersion_name = map[int32]string{
		0: "UNKNOWN_VER",
		1: "VERSION_1",
		2: "VERSION_2",
		3: "VERSION_3",
		4: "VERSION_4",
		5: "VERSION_5",
	}
	ProtoVersion_value = map[string]int32{
		"UNKNOWN_VER": 0,
		"VERSION_1":   1,
		"VERSION_2":   2,
		"VERSION_3":   3,
		"VERSION_4":   4,
		"VERSION_5":   5,
	}
)

func (x ProtoVersion) Enum() *ProtoVersion {
	p := new(ProtoVersion)
	*p = x
	return p
}

func (x ProtoVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_streaming_proto_enumTypes[0].Descriptor()
}

func (ProtoVersion) Type() protoreflect.EnumType {
	return &file_audio_streaming_proto_enumTypes[0]
}

func (x ProtoVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoVersion.Descriptor instead.
func (ProtoVersion) EnumDescriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{0}
}

type ResponseType int32

const (
	ResponseType_UNKNOWN_TYPE  ResponseType = 0
	ResponseType_FRAGMENT_DATA ResponseType = 1
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "FRAGMENT_DATA",
	}
	ResponseType_value = map[string]int32{
		"UNKNOWN_TYPE":  0,
		"FRAGMENT_DATA": 1,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_streaming_proto_enumTypes[1].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_audio_streaming_proto_enumTypes[1]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{1}
}

type InitRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EnableLongSpeech bool                   `protobuf:"varint,1,opt,name=enable_long_speech,json=enableLongSpeech,proto3" json:"enable_long_speech,omitempty"`
	EnableChunk      bool                   `protobuf:"varint,2,opt,name=enable_chunk,json=enableChunk,proto3" json:"enable_chunk,omitempty"`
	EnableFlushData  bool                   `protobuf:"varint,3,opt,name=enable_flush_data,json=enableFlushData,proto3" json:"enable_flush_data,omitempty"`
	ProductId        string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SamplePointBytes uint32                 `protobuf:"varint,5,opt,name=sample_point_bytes,json=samplePointBytes,proto3" json:"sample_point_bytes,omitempty"`
	SendPerSeconds   float64                `protobuf:"fixed64,6,opt,name=send_per_seconds,json=sendPerSeconds,proto3" json:"send_per_seconds,omitempty"`
	SleepRatio       float64                `protobuf:"fixed64,7,opt,name=sleep_ratio,json=sleepRatio,proto3" json:"sleep_ratio,omitempty"`
	AppName          string                 `protobuf:"bytes,8,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	LogLevel         uint32                 `protobuf:"varint,9,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	UserName         string                 `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ExpireTime       string                 `protobuf:"bytes,11,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Token            string                 `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	Version          ProtoVersion           `protobuf:"varint,13,opt,name=version,proto3,enum=com.baidu.acu.pie.ProtoVersion" json:"version,omitempty"`
	ExtraInfo        string                 `protobuf:"bytes,14,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	EnableVadPause   bool                   `protobuf:"varint,15,opt,name=enable_vad_pause,json=enableVadPause,proto3" json:"enable_vad_pause,omitempty"`
	VadPauseFrame    int32                  `protobuf:"varint,16,opt,name=vad_pause_frame,json=vadPauseFrame,proto3" json:"vad_pause_frame,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_audio_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetEnableLongSpeech() bool {
	if x != nil {
		return x.EnableLongSpeech
	}
	return false
}

func (x *InitRequest) GetEnableChunk() bool {
	if x != nil {
		return x.EnableChunk
	}
	return false
}

func (x *InitRequest) GetEnableFlushData() bool {
	if x != nil {
		return x.EnableFlushData
	}
	return false
}

func (x *InitRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitRequest) GetSamplePointBytes() uint32 {
	if x != nil {
		return x.SamplePointBytes
	}
	return 0
}

func (x *InitRequest) GetSendPerSeconds() float64 {
	if x != nil {
		return x.SendPerSeconds
	}
	return 0
}

func (x *InitRequest) GetSleepRatio() float64 {
	if x != nil {
		return x.SleepRatio
	}
	return 0
}

func (x *InitRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *InitRequest) GetLogLevel() uint32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *InitRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *InitRequest) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *InitRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InitRequest) GetVersion() ProtoVersion {
	if x != nil {
		return x.Version
	}
	return ProtoVersion_UNKNOWN_VER
}

func (x *InitRequest) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *InitRequest) GetEnableVadPause() bool {
	if x != nil {
		return x.EnableVadPause
	}
	return false
}

func (x *InitRequest) GetVadPauseFrame() int32 {
	if x != nil {
		return x.VadPauseFrame
	}
	return 0
}

type AudioFragmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   uint32                 `protobuf:"varint,1,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	SendTimestamp uint64                 `protobuf:"varint,2,opt,name=send_timestamp,json=sendTimestamp,proto3" json:"send_timestamp,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFragmentRequest) Reset() {
	*x = AudioFragmentRequest{}
	mi := &file_audio_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFragmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFragmentRequest) ProtoMessage() {}

func (x *AudioFragmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFragmentRequest.ProtoReflect.Descriptor instead.
func (*AudioFragmentRequest) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *AudioFragmentRequest) GetSequenceNum() uint32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AudioFragmentRequest) GetSendTimestamp() uint64 {
	if x != nil {
		return x.SendTimestamp
	}
	return 0
}

func (x *AudioFragmentRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type AudioFragmentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	SerialNum     string                 `protobuf:"bytes,5,opt,name=serial_num,json=serialNum,proto3" json:"serial_num,omitempty"`
	NoiseLevel    uint32                 `protobuf:"varint,6,opt,name=noise_level,json=noiseLevel,proto3" json:"noise_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFragmentResult) Reset() {
	*x = AudioFragmentResult{}
	mi := &file_audio_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFragmentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFragmentResult) ProtoMessage() {}

func (x *AudioFragmentResult) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFragmentResult.ProtoReflect.Descriptor instead.
func (*AudioFragmentResult) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *AudioFragmentResult) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AudioFragmentResult) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *AudioFragmentResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AudioFragmentResult) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *AudioFragmentResult) GetSerialNum() string {
	if x != nil {
		return x.SerialNum
	}
	return ""
}

func (x *AudioFragmentResult) GetNoiseLevel() uint32 {
	if x != nil {
		return x.NoiseLevel
	}
	return 0
}

type AudioFragmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Type          ResponseType           `protobuf:"varint,3,opt,name=type,proto3,enum=com.baidu.acu.pie.ResponseType" json:"type,omitempty"`
	AudioFragment *AudioFragmentResult   `protobuf:"bytes,4,opt,name=audio_fragment,json=audioFragment,proto3" json:"audio_fragment,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFragmentResponse) Reset() {
	*x = AudioFragmentResponse{}
	mi := &file_audio_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFragmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFragmentResponse) ProtoMessage() {}

func (x *AudioFragmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFragmentResponse.ProtoReflect.Descriptor instead.
func (*AudioFragmentResponse) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *AudioFragmentResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *AudioFragmentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AudioFragmentResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_UNKNOWN_TYPE
}

func (x *AudioFragmentResponse) GetAudioFragment() *AudioFragmentResult {
	if x != nil {
		return x.AudioFragment
	}
	return nil
}

func (x *AudioFragmentResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_audio_streaming_proto protoreflect.FileDescriptor

const file_audio_streaming_proto_rawDesc = "" +
	"\n" +
	"\x15audio_streaming.proto\x12\x11com.baidu.acu.pie\"\xda\x04\n" +
	"\vInitRequest\x12,\n" +
	"\x12enable_long_speech\x18\x01 \x01(\bR\x10enableLongSpeech\x12!\n" +
	"\fenable_chunk\x18\x02 \x01(\bR\venableChunk\x12*\n" +
	"\x11enable_flush_data\x18\x03 \x01(\bR\x0fenableFlushData\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12,\n" +
	"\x12sample_point_bytes\x18\x05 \x01(\rR\x10samplePointBytes\x12(\n" +
	"\x10send_per_seconds\x18\x06 \x01(\x01R\x0esendPerSeconds\x12\x1f\n" +
	"\vsleep_ratio\x18\a \x01(\x01R\n" +
	"sleepRatio\x12\x19\n" +
	"\bapp_name\x18\b \x01(\tR\aappName\x12\x1b\n" +
	"\tlog_level\x18\t \x01(\rR\blogLevel\x12\x1b\n" +
	"\tuser_name\x18\n" +
	" \x01(\tR\buserName\x12\x1f\n" +
	"\vexpire_time\x18\v \x01(\tR\n" +
	"expireTime\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token\x129\n" +
	"\aversion\x18\r \x01(\x0e2\x1f.com.baidu.acu.pie.ProtoVersionR\aversion\x12\x1d\n" +
	"\n" +
	"extra_info\x18\x0e \x01(\tR\textraInfo\x12(\n" +
	"\x10enable_vad_pause\x18\x0f \x01(\bR\x0eenableVadPause\x12&\n" +
	"\x0fvad_pause_frame\x18\x10 \x01(\x05R\rvadPauseFrame\"\x7f\n" +
	"\x14AudioFragmentRequest\x12!\n" +
	"\fsequence_num\x18\x01 \x01(\rR\vsequenceNum\x12%\n" +
	"\x0esend_timestamp\x18\x02 \x01(\x04R\rsendTimestamp\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\"\xc5\x01\n" +
	"\x13AudioFragmentResult\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12\x1d\n" +
	"\n" +
	"serial_num\x18\x05 \x01(\tR\tserialNum\x12\x1f\n" +
	"\vnoise_level\x18\x06 \x01(\rR\n" +
	"noiseLevel\"\xfa\x01\n" +
	"\x15AudioFragmentResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.com.baidu.acu.pie.ResponseTypeR\x04type\x12M\n" +
	"\x0eaudio_fragment\x18\x04 \x01(\v2&.com.baidu.acu.pie.AudioFragmentResultR\raudioFragment\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId*j\n" +
	"\fProtoVersion\x12\x0f\n" +
	"\vUNKNOWN_VER\x10\x00\x12\r\n" +
	"\tVERSION_1\x10\x01\x12\r\n" +
	"\tVERSION_2\x10\x02\x12\r\n" +
	"\tVERSION_3\x10\x03\x12\r\n" +
	"\tVERSION_4\x10\x04\x12\r\n" +
	"\tVERSION_5\x10\x05*3\n" +
	"\fResponseType\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x11\n" +
	"\rFRAGMENT_DATA\x10\x012k\n" +
	"\n" +
	"AsrService\x12]\n" +
	"\x04send\x12'.com.baidu.acu.pie.AudioFragmentRequest\x1a(.com.baidu.acu.pie.AudioFragmentResponse(\x010\x01B\fZ\n" +
	"./protogenb\x06proto3"

var (
	file_audio_streaming_proto_rawDescOnce sync.Once
	file_audio_streaming_proto_rawDescData []byte
)

func file_audio_streaming_proto_rawDescGZIP() []byte {
	file_audio_streaming_proto_rawDescOnce.Do(func() {
		file_audio_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)))
	})
	return file_audio_streaming_proto_rawDescData
}

var file_audio_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_audio_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_audio_streaming_proto_goTypes = []any{
	(ProtoVersion)(0),             // 0: com.baidu.acu.pie.ProtoVersion
	(ResponseType)(0),             // 1: com.baidu.acu.pie.ResponseType
	(*InitRequest)(nil),           // 2: com.baidu.acu.pie.InitRequest
	(*AudioFragmentRequest)(nil),  // 3: com.baidu.acu.pie.AudioFragmentRequest
	(*AudioFragmentResult)(nil),   // 4: com.baidu.acu.pie.AudioFragmentResult
	(*AudioFragmentResponse)(nil), // 5: com.baidu.acu.pie.AudioFragmentResponse
}
var file_audio_streaming_proto_depIdxs = []int32{
	0, // 0: com.baidu.acu.pie.InitRequest.version:type_name -> com.baidu.acu.pie.ProtoVersion
	1, // 1: com.baidu.acu.pie.AudioFragmentResponse.type:type_name -> com.baidu.acu.pie.ResponseType
	4, // 2: com.baidu.acu.pie.AudioFragmentResponse.audio_fragment:type_name -> com.baidu.acu.pie.AudioFragmentResult
	3, // 3: com.baidu.acu.pie.AsrService.send:input_type -> com.baidu.acu.pie.AudioFragmentRequest
	5, // 4: com.baidu.acu.pie.AsrService.send:output_type -> com.baidu.acu.pie.AudioFragmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audio_streaming_proto_init() }
func file_audio_streaming_proto_init() {
	if File_audio_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_streaming_proto_goTypes,
		DependencyIndexes: file_audio_streaming_proto_depIdxs,
		EnumInfos:         file_audio_streaming_proto_enumTypes,
		MessageInfos:      file_audio_streaming_proto_msgTypes,
	}.Build()
	File_audio_streaming_proto = out.File
	file_audio_streaming_proto_goTypes = nil
	file_audio_streaming_proto_depIdxs = nil
}
