platform :ios,'8.0'

def commonPods
    pod '!ProtoCompiler'
    pod '!ProtoCompiler-gRPCPlugin'
    pod 'BoringSSL-GRPC'
    pod 'Protobuf'
    pod 'gRPC'
    pod 'gRPC-Core'
    pod 'gRPC-ProtoRPC'
    pod 'gRPC-RxLibrary'
    pod 'nanopb'
end

workspace 'BaiduASR.xcworkspace'

target 'BaiduASR' do
    project 'BaiduASR/BaiduASR.xcodeproj'
    commonPods
end

target 'BaiduASRDemo' do
    project 'BaiduASRDemo.xcodeproj'
end
