platform :ios,'8.0'
target 'BaiduARS' do
    
pod '!ProtoCompiler'
pod '!ProtoCompiler-gRPCPlugin'
pod 'BoringSSL-GRPC'
pod 'Protobuf'
pod 'gRPC'
pod 'gRPC-Core'
pod 'gRPC-ProtoRPC'
pod 'gRPC-RxLibrary'
pod 'nanopb'
pod 'Novocaine'

end
