# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import audio_streaming_pb2 as audio__streaming__pb2


class AsrServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send = channel.stream_stream(
        '/com.baidu.acu.pie.AsrService/send',
        request_serializer=audio__streaming__pb2.AudioFragmentRequest.SerializeToString,
        response_deserializer=audio__streaming__pb2.AudioFragmentResponse.FromString,
        )


class AsrServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AsrServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send': grpc.stream_stream_rpc_method_handler(
          servicer.send,
          request_deserializer=audio__streaming__pb2.AudioFragmentRequest.FromString,
          response_serializer=audio__streaming__pb2.AudioFragmentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.baidu.acu.pie.AsrService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
